keys:
  - &admin age1yxu5s22t3ggg4zspmklv58893kaf5vmzu2erk8t9dmamdquaxffq3lwmp4
  - &mbp2 age1kslu8m2ywet3fe9dr7ehqqsz7mkg0ugj6jdhh8m6rdd5erakkuusyx0sx2
  
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *admin
      - *mbp2
