#+TITLE: Wie benutzt man sops
#+AUTHOR: Axel Ramge
#+DATE: 2026-03-29

* Sops verschlüsseln

=sops= sucht in der =.sops.yaml= nach den richtigen Schlüsseln zum Verschlüsseln. Die Datei kann gefahrlos öffentlich lesbar sein. Die Keys sind öffentlich.

#+BEGIN_SRC yaml
keys:
  - &admin age1yxu5s22t3ggg4zspmklv58893kaf5vmzu2erk8t9dmamdquaxffq3lwmp4
  - &mbp2 age1kslu8m2ywet3fe9dr7ehqqsz7mkg0ugj6jdhh8m6rdd5erakkuusyx0sx2
  # - &mbp3 age1... (wird hier später ergänzt)

creation_rules:
  # Host-spezifische Regeln: Greifen exakt für die Datei des jeweiligen Hosts
  - path_regex: secrets/mbp2\.yaml$
    key_groups:
    - age:
      - *admin
      - *mbp2

  # - path_regex: secrets/mbp3\.yaml$
  #   key_groups:
  #   - age:
  #     - *admin
  #     - *mbp3

  # Fallback-Regel: Greift für alle anderen YAML-Dateien (z. B. deine rclone.yml)
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *admin
      - *mbp2 # Ggf. anpassen, je nachdem wer auf rclone zugreifen soll
#+END_SRC

Um den Inhalt in eine verschlüsselte Datei zu "injizieren" ohne sie auch nur temporär auf Datenträger zu schreiben kann man folgendes Konstrukt verwenden. Die Option =--filename-override= ist dazu da, =sops= mitzuteilen, für welche Ziele das Geheimnis verschlüsselt werden soll. Es vergleicht den Dateinamen mit der =.sops.yaml=, da er den echten Dateinamen ja nicht kennt, wenn er von =stdin= liest.

#+BEGIN_SRC shell
  ramge@mbp2:~/sync/gh/nixos $ echo "wg_private_key: SuperStrengGeheimVerschlusssacheNurfürdenDienstgebrauch="  | sops encrypt --filename-override secrets/mbp2.yaml > secrets/mbp2.yaml
#+END_SRC

* Sops entschlüsseln

Für die Entschlüsselung ist der private Schlüssel erforderlich. Der wird so in eine Shell-Variable geschrieben:


#+BEGIN_SRC shell
  ramge@mbp2:~/sync/gh/nixos $ export SOPS_AGE_KEY=$(keepassxc-cli show -q -a Password ~/sync/gh/secrets/keepassxc/ramge.kdbx "sops-age-key")
#+END_SRC

und steht dann für die Entschlüsselung zur Verfügung

#+BEGIN_SRC shell
ramge@mbp2:~/sync/gh/nixos $ sops decrypt secrets/mbp2.yaml
#+END_SRC
